# Build a self-contained wheelhouse for air-gapped installs (Windows).
#
#   powershell -ExecutionPolicy Bypass -File tools\make_wheelhouse.ps1 OUT_DIR [-Cuda cu128] [-PythonVersion 3.12]
#
# Run on a CONNECTED machine. Copy OUT_DIR and the model to the target, then
#   powershell -ExecutionPolicy Bypass -File install.ps1 -Offline OUT_DIR
param(
    [Parameter(Mandatory = $true)][string]$OutDir,
    [string]$Cuda = "cu128",
    [string]$PythonVersion = "3.12"
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
New-Item -ItemType Directory -Force $OutDir | Out-Null
$OutDir = (Resolve-Path $OutDir).Path
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) { throw "uv required" }

$work = Join-Path $env:TEMP ("moge-wheelhouse-" + [guid]::NewGuid().ToString("N").Substring(0, 8))
New-Item -ItemType Directory -Force $work | Out-Null
$env:VIRTUAL_ENV = Join-Path $work "venv"
uv venv --python $PythonVersion $env:VIRTUAL_ENV | Out-Null
uv pip install --quiet pip
$py = Join-Path $env:VIRTUAL_ENV "Scripts\python.exe"

uv pip install --quiet torch torchvision --index-url "https://download.pytorch.org/whl/$Cuda"
uv pip install --quiet -e (Join-Path $root "third_party\MoGe")
uv pip install --quiet triton-windows safetensors "opencv-python-headless<5"

$freeze = (uv pip freeze --exclude-editable) | Where-Object { $_ -notmatch "^-e " }
$freeze | Set-Content (Join-Path $work "freeze.txt") -Encoding ASCII
$req = @("# generated by tools\make_wheelhouse.ps1 ($(Get-Date -Format yyyy-MM-dd)) cuda=$Cuda python=$PythonVersion")
# "pkg @ git+https://..." -> "pkg": the wheel built below satisfies it offline
$req += $freeze | ForEach-Object { $_ -replace "^([A-Za-z0-9_.-]+) @ git\+.*$", '$1' }
$req | Set-Content (Join-Path $OutDir "requirements.txt") -Encoding ASCII

Write-Host "building / downloading wheels into $OutDir ..."
& $py -m pip wheel --quiet --wheel-dir $OutDir --index-url "https://download.pytorch.org/whl/$Cuda" --extra-index-url https://pypi.org/simple -r (Join-Path $work "freeze.txt")
if ($LASTEXITCODE) { throw "pip wheel failed" }
& $py -m pip download --quiet --dest $OutDir --index-url https://pypi.org/simple pip setuptools wheel
Remove-Item -Recurse -Force $work
Copy-Item (Join-Path $root "docs\OFFLINE.md") (Join-Path $OutDir "README-OFFLINE.md") -ErrorAction SilentlyContinue
Write-Host "wheelhouse ready: $((Get-ChildItem $OutDir -Filter *.whl).Count) wheels"
Write-Host "next: copy $OutDir + models\moge-3-vitg.* to the target, then install.ps1 -Offline <dir>"
