#!/usr/bin/env bash
# Build a self-contained wheelhouse for air-gapped installs (Linux).
#
#   tools/make_wheelhouse.sh OUT_DIR [--cuda cu128] [--python 3.12]
#
# Run on a CONNECTED machine with the same OS family / Python minor version as
# the target. Produces OUT_DIR/ with every wheel the install needs (torch,
# Triton, MoGe's GitHub dependencies built into wheels) plus requirements.txt,
# then copy OUT_DIR and the model checkpoint to the target and run
#   ./install.sh --offline OUT_DIR
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ $# -ge 1 ] || { sed -n '2,11p' "$0"; exit 2; }
out="$(mkdir -p "$1" && cd "$1" && pwd)"; shift
cuda="cu128"; pyver="3.12"
while [ $# -gt 0 ]; do
    case "$1" in
        --cuda) cuda="$2"; shift 2 ;;
        --python) pyver="$2"; shift 2 ;;
        *) echo "unknown option $1" >&2; exit 2 ;;
    esac
done
command -v uv >/dev/null || { echo "uv required" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
export VIRTUAL_ENV="$work/venv"
uv venv --python "$pyver" "$VIRTUAL_ENV" >/dev/null
uv pip install --quiet pip
py="$VIRTUAL_ENV/bin/python"

# resolve exactly what install.sh would install
uv pip install --quiet torch torchvision --index-url "https://download.pytorch.org/whl/$cuda"
uv pip install --quiet -e "$root/third_party/MoGe"
uv pip install --quiet triton safetensors "opencv-python-headless<5"

# pin everything except the editable moge; git deps are built into wheels below
uv pip freeze --exclude-editable | grep -v '^-e ' > "$work/freeze.txt"
{
    echo "# generated by tools/make_wheelhouse.sh ($(date -u +%F)) cuda=$cuda python=$pyver"
    # "pkg @ git+https://..." -> "pkg": the wheel built below satisfies it offline
    sed -E 's/^([A-Za-z0-9_.-]+) @ git\+.*$/\1/' "$work/freeze.txt"
} > "$out/requirements.txt"

echo "building / downloading wheels into $out ..."
"$py" -m pip wheel --quiet --wheel-dir "$out" \
    --index-url "https://download.pytorch.org/whl/$cuda" --extra-index-url https://pypi.org/simple \
    -r "$work/freeze.txt"
# tools install.sh itself may need offline
"$py" -m pip download --quiet --dest "$out" --index-url https://pypi.org/simple pip setuptools wheel

cp "$root/docs/OFFLINE.md" "$out/README-OFFLINE.md" 2>/dev/null || true
echo "wheelhouse ready: $(ls "$out"/*.whl | wc -l) wheels, $(du -sh "$out" | cut -f1)"
echo "next: copy $out + models/moge-3-vitg.* to the target, then ./install.sh --offline <dir>"
